version :'1'

services:
  node:
    build: .
    ports:
      - "8080:8080"
    networks:
      - nodeapp-network
    depends_on:
      - mongodb

  mongodb:
    image: doramart/dora-mongo
    networks:
      - nodeapp-network

  mongo_seed:
    image: doramart/dora-mongo
    links:
      - mongodb
    networks:
      - nodeapp-network
    command:
      - mongorestore --host mongodb -d demodoracms --drop ./app/databak/demodoracms

networks:
  nodeapp-network:
    driver: bridge
